server:
  port: 80
#    address: 192.168.100.130
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medical_system
    username: root
    password: 123456


  mvc:

    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

    static-path-pattern: /static/**
    static-locations: classpath:/
